services:
    # Data validator
    drsoft_fr.module.validate_customer.data.validator.setting_validator:
        class: DrSoftFr\Module\ValidateCustomer\Data\Validator\SettingValidator
        arguments:
            - '@drsoft_fr.module.validate_customer.adapter.query_handler.cms_page.get_id_cms_pages_provider'

    # Data factory
    drsoft_fr.module.validate_customer.data.factory.setting_data_factory:
        class: DrSoftFr\Module\ValidateCustomer\Data\Factory\SettingDataFactory
        arguments:
            - '@drsoft_fr.module.validate_customer.data.configuration.setting_configuration'

    # Data provider
    drsoft_fr.module.validate_customer.data.configuration.setting_configuration:
        class: DrSoftFr\Module\ValidateCustomer\Data\Configuration\SettingConfiguration
        arguments:
            - '@prestashop.adapter.legacy.configuration'
            - '@drsoft_fr.module.validate_customer.data.validator.setting_validator'
        public: true

    drsoft_fr.module.validate_customer.data.setting_data_provider:
        class: DrSoftFr\Module\ValidateCustomer\Data\Factory\SettingDataFactory
        factory: 'drsoft_fr.module.validate_customer.data.factory.setting_data_factory:getData'
        public: true
